### PR TITLE
fix the logging how to fix uncommited changes

### LINKED ISSUE #383: Include uncommited changes fix does not show previously used parameters
If I have already changes some things and do
`mob start -b green`
then I get an error because I need to include the uncommited changes. The suggested command is `mob start --include-uncommited-changes`. In my opinion the suggestion should be mob start --include-uncommited-changes -b green`.

### PR DESCRIPTION
**Pull request by hollesse**
closes #383

### CODE REVIEW

File: mob_test.go [hunk 1]
```diff
@@ -1396,6 +1396,54 @@ func TestStartNextPushManualCommits(t *testing.T) {
...
+	runMob(t, tempDir+"/local", "start", "-b", "green")
+
+	assertOutputContains(t, output, "mob start --branch green --include-uncommitted-changes")
+}
+
+func TestStartBranchEnvWithUncommitedChangesFixWithoutBranch(t *testing.T) {
+	output, _ := setup(t)
+
+	setWorkingDir(tempDir + "/local")
+	os.Setenv("MOB_WIP_BRANCH_QUALIFIER", "red")
```
Comment (gregorriegler) [inline mob_test.go:1414]: I think we should be using `t.Setenv` instead

**Review by gregorriegler — CHANGES_REQUESTED** [review]
other than my comment it looks good to me

**Comment by hollesse** [comment]
I needed to update the go version to use t.setEnv

**Review by gregorriegler — APPROVED** [review]
